export const copy = {
  lirnName: "LIRN",
  tornsName: "TORNS",
  byLirn: "by LIRN",
  oficio: "Empresa de movilidad",
  mission:
    "Hacer que el transporte masivo ajuste su oferta a la demanda real de cada estación, midiendo quién espera ahora y no solo lo que el horario predijo.",
  vision:
    "Que cada estación de un sistema masivo opere con la demanda que ocurre, no con la que se supuso.",
  heroHeadline: "La demanda no espera.",
  heroSupport:
    "LIRN hace que el transporte masivo responda a lo que ocurre en estación.",
  ctaTalk: "Hablemos",
  verTorns: "Ver TORNS",
  navLirn: "LIRN",
  navTorns: "TORNS",
  navEmpresa: "Empresa",
  navContacto: "Contacto",
  companyTitle: "Quiénes somos",
  companyBody:
    "LIRN es una firma de movilidad. Un producto. Sistemas masivos con estaciones.",
  purposeTitle: "Propósito",
  missionLabel: "Misión",
  visionLabel: "Visión",
  capabilityTitle: "Capacidad",
  capMeasure: "Medir",
  capMeasureBody:
    "Quién espera ahora en la estación, no solo lo que el horario predijo.",
  capSee: "Ver",
  capSeeBody: "Ocupación que ocurre, visible para quien decide la oferta.",
  capRecommend: "Recomendar",
  capRecommendBody: "Frecuencia y capacidad propuestas al centro de control.",
  teaserTitle: "TORNS",
  teaserBody: "La oferta no sigue a la demanda real en estación.",
  teaserLead: "Producto de LIRN para el centro de control.",
  contactTitle: "Hablemos del sistema que opera.",
  contactBody:
    "Cuéntenos el sistema masivo y el rol de control. Publicaremos el canal de contacto cuando esté listo.",
  contactNote: "Canal de envío pendiente de publicar.",
  footerBlurb: "Firma de movilidad. Producto TORNS.",
  tornsHeadline: "Demanda real en estación. Recomendación al control.",
  tornsSupport:
    "TORNS mide la demanda en estación y propone oferta al centro de control.",
  problemTitle: "El problema",
  problemBody:
    "En Bogotá, los usuarios del transporte público se enfrentan diariamente a estaciones y trenes con diferentes niveles de congestión. En algunos momentos, la cantidad de pasajeros supera la capacidad disponible, generando largas esperas y viajes incómodos. Esto ocurre porque la cantidad y frecuencia del Transmilenio no siempre se ajusta a la demanda real de pasajeros en cada momento. Esta situación afecta directamente la experiencia de los usuarios y dificulta que puedan llegar a sus destinos de manera rápida y cómoda.",
  problemExpected: "Demanda prevista",
  problemReal: "Demanda real",
  caseFrame:
    "Caso de estudio y prototipo aplicado al problema de Transmilenio.",
  caseNotPilot: "No es un piloto firmado con el operador.",
  caseScope: "Los mismos fundamentos aplican a metro, BRT o tren.",
  storyTitle: "De la estación al despacho",
  storyWaitTitle: "La estación no espera",
  storyWaitBody:
    "La oferta se fija por horario e histórico. El andén cambia. Quien espera paga el desajuste.",
  storySeeTitle: "La cámara ve la estación",
  storySeeBody:
    "TORNS toma la estación como fuente. Cámaras por andén. Presencia visible, no un promedio.",
  storyMeasureTitle: "La demanda se cuenta",
  storyMeasureBody:
    "YOLOv11 detecta y cuenta quién está ahora. Frames y métricas viajan por WebSocket.",
  storyActTitle: "El control recibe la oferta",
  storyActBody:
    "Frecuencia y capacidad propuestas al despacho. El operador ve ocupación y actúa.",
  systemTitle: "Cómo funciona",
  systemSteps: [
    "Observar",
    "Detectar",
    "Medir",
    "Analizar",
    "Recomendar",
    "Optimizar",
  ],
  systemStepBodies: [
    "Cámara en estación.",
    "Persona en el andén.",
    "Conteo de demanda.",
    "Estado por estación.",
    "Frecuencia y capacidad.",
    "Ajuste de oferta.",
  ],
  capabilitiesTitle: "El prototipo",
  cap1: "Fuentes de video por estación",
  cap2: "Detección y conteo en vivo (YOLOv11)",
  cap3: "Frames y métricas por WebSocket",
  cap4: "Recomendación de despacho",
  discoveryTitle: "Descubrimiento",
  validationTitle: "Validación",
  validationLead: "Encuesta · n=20",
  close: "Cualquier sistema masivo con estaciones.",
  chapterProduct: "Producto",
  chapterSystem: "Sistema",
  chapterCase: "Caso",
  chapterClose: "Cierre",
  questionProgress: "Pregunta {n} de 10",
  controlPrev: "Anterior",
  controlNext: "Siguiente",
  detectHint: "Detección, no un conteo de operador.",
  actEspera: "Espera",
  actVe: "Ve",
  actMide: "Mide",
  actActua: "Actúa",
  chapterEmpresa: "Empresa",
  chapterContact: "Contacto",
  teamMembers: [
    "Johel Santiago Arias",
    "Rebeca Pedrozo",
    "Hanna Cerinza",
  ] as const,
  contactFormTitle: "Contacto",
  contactFormBody:
    "Cuéntenos el sistema masivo y el rol de control. Le respondemos por este canal.",
  contactNameLabel: "Nombre",
  contactEmailLabel: "Email",
  contactOrgLabel: "Organización",
  contactMessageLabel: "Mensaje",
  contactSubmit: "Enviar",
  contactSending: "Enviando…",
  contactSuccess: "Recibimos su mensaje. Gracias.",
  contactError: "No pudimos enviar. Intente de nuevo.",
  contactMissingEndpoint: "Canal de envío no configurado.",
  contactRequired: "Campo obligatorio.",
  contactInvalidEmail: "Email no válido.",
  notFound: "Esta página no existe.",
} as const;
