export const copy = {
  lirnName: "LIRN",
  oficio: "Empresa de movilidad",
  mission: "Hacer que el transporte masivo ajuste su oferta a la demanda real de cada estación, midiendo quién espera ahora y no solo lo que el horario predijo.",
  vision: "Que cada estación de un sistema masivo opere con la demanda que ocurre, no con la que se supuso.",
  tornsName: "TORNS",
  byLirn: "by LIRN",
  tornsOficio: "Demanda real en estación. Oferta ajustada al control.",
  productWhat: "Demanda medida en estación. Recomendación de oferta al centro de control.",
  whyTitle: "La oferta no sigue a la estación",
  whyBody: "En un sistema masivo, la frecuencia y la capacidad se fijan por horario e histórico. La estación cambia. Una se satura. Otra viaja vacía. Quien espera paga el desajuste.",
  whyFoot: "Contexto: congestión y desajuste de oferta en Transmilenio, Bogotá. Problema público. No es un piloto ni un cliente.",
  problemLabel: "PROBLEMA",
  solutionLabel: "SOLUCIÓN",
  solutionTitle: "TORNS mide la estación y recomienda la oferta",
  solutionBody: "Cámaras en estación. Conteo de demanda. Recomendación de frecuencia y capacidad al centro de control. El operador ve ocupación, no un promedio.",
  factOccupation: "Ve la ocupación.",
  factCamera: "Ve la cámara con detección.",
  factRecommend: "Recibe la recomendación.",
  limit: "Prototipo. No hay piloto firmado.",
  qrLegend: "Abrir la landing de TORNS",
  tornsByLirn: "TORNS by LIRN",
  close: "Cualquier sistema masivo con estaciones.",
  notFound: "Esta página no existe.",
  navLirn: "LIRN",
  navTorns: "TORNS",
} as const;
